### ISSUE TITLE
Talk review page for speaker feedback - clarification

### ISSUE THREAD

**Issue by willingc** [PyCon/pycon#357]
It would be helpful to remind talk reviewers that their name will be sent to the talk proposer when the system emails the proposer.

**Comment by brandon-rhodes** [comment]
From what I can see of the code and the commit history, this change never quite landed in the code base? Since the Talks committee is not using the main PyCon app to do its reviewing in 2016, but a separate custom app, my guess is that we can safely close this issue for now. Feel free to re-open it if at any point you want to revive this issue and revisit the idea of adding more text to the message!

**Comment by willingc** [comment]
@brandon-rhodes +1 to the clean-up efforts :-)

**Comment by brandon-rhodes** [comment]
Thank you, @willingc! :)
