### ISSUE TITLE
Fix the expunge_delete cron job

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#376]

**Comment by calebsmith** [comment]
Just making some quick notes here while it's on the top of my head.

Using the steps that Chef does here: https://github.com/python/psf-chef/blob/master/cookbooks/psf-pycon/recipes/app.rb#L112 I'm able to run the script without issue. There were no deleted accounts at the time though, so I only saw 0 in the output.

Following up with Rebecca and David on this, and it appears that in the past accounts weren't reliably deleted so it was suspected that this cron wasn't working.

However, looking at /var/log/syslog, I'm able to see that the job ran last night as well as the other cronjob for the Pycon site. However, there is one oddity which is that 'crontab -l' is showing some other cron jobs set by Chef, but not these two specific to the pycon app. Maybe I'm misunderstanding crontab here, but I would expect to see all 4.

The other issue is that the output of the cronjobs aren't emailed because postfix isn't set up, but MAILTO isn't set for the jobs either, so the output is abandoned. I'm considering using redirection so that expunge_deleted has a log for its output so we can see if its working. One approach would be to get this in place and create some test accounts on staging, set them to deleted and see if it comes through.

**Comment by dpoirier** [comment]
`crontab -l` will only show cron jobs specifically owned by the current user. You can see another user's cron jobs with `sudo crontab -u USERNAME -l`, if you know the username to look for. There are also systemwide places to configure cron jobs that won't show up in user crontabs. 

User crontabs are probably under `/var/spool/cron/crontabs`.  Also look in `/etc/cron.*` for other directories of cron files.

**Comment by dpoirier** [comment]
This is definitely running on the new Rackspace servers, and I've added redirecting of the output to a log file for each Pycon cron job (there are two) so we can be sure they're still running and see if anything goes wrong.
