### ISSUE TITLE
Update the settings file used by production and stagings sites 

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#377]
To the one that we're maintaining.

**Comment by calebsmith** [comment]
The settings in staging and production use this ERB template from psf-chef: 

https://github.com/python/psf-chef/blob/master/cookbooks/psf-pycon/templates/default/local_settings.py.erb

The approach taken with using that Chef setup seems fine to me. Do we want to get rid of that and use our staging/production files? Otherwise, do we want to just delete the staging, production, and server settings files sense these are setup and working from psf-chef?

**Comment by dpoirier** [comment]
Sticking with the Chef template - and removing the confusing unused other settings files - sounds fine to me.

**Comment by calebsmith** [comment]
It appears I was mistaken.

Though Chef generates this local_settings file, I can't see it getting imported or used anywhere. Running a manage.py shell on staging shows that our staging setting is being loaded. I can confirm that the settings that Chef creates such as GRAYLOG_HOST aren't used anywhere.

I think we can close this ticket and move on with the understanding that production, staging, and by extension server, settings are being used for the project. We might consider removing the bit from psf-chef that adds the local_settings.py file in order to avoid confusion

**Comment by dpoirier** [comment]
Definite +1 for cleaning up the unused bits from psf-chef (after making sure we really don't need any of them).

**Comment by calebsmith** [comment]
I've assigned this to myself. Going to take a look at addressing this in psf-chef soon

**Comment by dpoirier** [comment]
@calebsmith do you think you'll get to this?  or should I reassign it?

**Comment by calebsmith** [comment]
yes, I can try to get the PR going for this today. Sorry for delay

**Comment by calebsmith** [comment]
Opened that PR but it appears we are moving to rackspace/salt so it maybe a non-issue. Will leave open until that happens or some further resolution

**Comment by dpoirier** [comment]
This is moot with the move to Salt/Rackspace.
