### ISSUE TITLE
Financial aid state Machine Interface

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#385]

**Comment by dpoirier** [comment]
Ben found this diagram in base camp; not a lot of prose to go with it, though:

![states](https://cloud.githubusercontent.com/assets/2788679/8849385/221f607a-310d-11e5-980f-c3bfe7475f94.png)

**Comment by lvh** [comment]
I made that diagram, so hopefully I can explain. There was some more explanation when I posted it though :)

These are states that a financial aid application can be in. Solid arcs are transitions that PyCon financial aid admins do. E.g. from submitted, we can put it in "information needed" or "offered". Dashed lines are things the applicants themselves do, e.g. once in "offered", an applicant can choose to accept or decline the offer.

It'd be super great if applicants can do this themselves through the website; right now they e-mail us and we manually adjust their application. I figure the easiest way would be a set of buttons depending on the current state, e.g., when offered, the applicant sees a "Decline" and "Accept" button.

Does that clarify what's going on?

**Comment by dpoirier** [comment]
I think I understand now.  We should be able to add buttons depending on the current state.

**Comment by dpoirier** [comment]
@lvh Is there any reason to deny someone who has withdrawn their application from submitting it again, providing the application period is still open?

Are there any other states that appear final in the diagram that should allow submitting again?  (E.g. declined? rejected?) again providing applications are still open?  (Or maybe the question doesn't arise because applications close before offers go out?)

**Comment by lvh** [comment]
Withdrawn => submitted is reasonable; the other two should definitely be final. I'm okay with having to do withdrawal => submitted manually for the paper trail; it's about 1-2 folks each year.
