### ISSUE TITLE
Refactor existing API views to use Django Rest Framework

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#391]

**Comment by dpoirier** [comment]
Question: this sounds like just an internal implementation detail. What's the expected benefit to the client?

**Comment by wolever** [comment]
I was linked to this issue too — is there some way I could help flesh out use cases? (although, for the very little it's worth, my gut feeling is that there wouldn't be much value in moving to DRF).

**Comment by dpoirier** [comment]
My gut is with yours. Although the current API implementation is entirely ad-hoc with views scattered here and there, it works well enough (or nobody has made specific complaints, anyway).

**Comment by wolever** [comment]
Yep. And, as far as I know, there are only a handful of people who consume the APIs, and they do it with ad-hoc scripts each year (off the top of my head: PyVideo to grab metadata about talks, myself to create session staff material, probably Luke to do program stuff, and probably Noah because IIRC he knew a bit about what was up, and possibly Felix(?) to do the mobile schedule)… so, as much as I hate to say it, there really won't be a lot of person-hours saved by improving the APIs, at least as they are used right now.

**Comment by dpoirier** [comment]
I think the other big user is, or has been, the proposal review team. They've used the APIs to group proposals into Thunderdome Groups and preserve IRC discussions and votes.

**Comment by dpoirier** [comment]
Then maybe we should just drop this?  And use #392 to improve the documentation of the existing API endpoints?

**Comment by wolever** [comment]
Yep, that's probably going to be the best bang-for-the-buck.

Also, I haven't forgotten about the updates I owe you on the other issues. I'll be getting them some time this week.

**Comment by ejodlowska** [comment]
Hi @wolever  - have you had a chance to provide the supplemental information?

**Comment by dpoirier** [comment]
Closing this per @ejodlowska and @wolever.
