### ISSUE TITLE
Hard-code 3 emails

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#401]
Hard-code three emails: conference chair, event coordinator, mobile guide organizer

**Comment by dpoirier** [comment]
What are we to do with these 3 addresses?

**Comment by ejodlowska** [comment]
@dpoirier Hi Dan - you can disregard this and see the other issue I left a comment on. It may be best for it to go to pycon-staff@ so you do not have to change it every show since that email address will stay active even after staff turnover. Let me know if you have any other questions on this request.

**Comment by dpoirier** [comment]
Closing; requirement was dropped.
