### ISSUE TITLE
Presentation email

### ISSUE THREAD

**Issue by briseling** [PyCon/pycon#402]
Use signal on Presentation save/delete to send email to users

**Comment by dpoirier** [comment]
Which users? What needs to be in the email?

**Comment by ejodlowska** [comment]
@dpoirier @brandon-rhodes 
These notifications can be sent to pycon-staff@python.org. These changes only become relevant 1.5 month out from the conference due to the signs that need to be printed and schedules that need to be printed and also the mobile guide. Can we have this task start 1.5 month out? If not, let me know and I can think of a better email address to send the changes to. The email should include a link to the presentation that was changed and perhaps a dump of what is there now: speaker, description, abstract. I would think that is easier to implement than showing exactly what was updated?

**Comment by ejodlowska** [comment]
@dpoirier Oh and if it could have a day/time stamp of when this change was made, this will help us stay organized especially if someone makes multiple changes in a 5 minute span.

**Comment by hatlas** [comment]
Doesn't seem to be functioning on staging at present.

I created a presentation, edited a presentation, deleted a presentation, etc., but no email seems to have gone out.

**Comment by ejodlowska** [comment]
Hi Hayley - this functionality is working. Those emails get sent to us and
not to you. They are notifications that someone has made changes to their
presentation so if need be we can make changes to our signs/mobile app/etc.

example:
Hayley Atlas has just updated the following presentation: *#878 Kittendome
Test Presentation (?)* at Sept. 10, 2015, 2:42 p.m.. Currently the
presentation consists of: Title: "Kittendome Test Presentation" Speaker:
Description: desc Abstract: abstract

Best regards,

Ewa
Director of Operations
Python Software Foundation
Cell: 415-319-5237

**Comment by hatlas** [comment]
OK - functionality is actually working. Closing ticket now. Thanks, @ejodlowska!
