### ISSUE TITLE
Final Fixes Part 2

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#560]
- [x] The "look at past PyCons" image viewer — as before — has a little vertical scroll bar next to it instead of simply filling its space completely.

In addition, as I hit right-arrow it does not scroll through as many images as it promises, and even seems to stop halfway between images.

 - [x] Fix registration banner on home page. The ends get cut off on firefox at a variety of screen widths.

**Comment by hatlas** [comment]
Registration banner ends get cut off in FF at 320x480:
![screen shot 2015-09-24 at 2 44 05 pm](https://cloud.githubusercontent.com/assets/8808771/10083070/beb83472-62ca-11e5-94db-058dbd8c4b19.png)
However, the slideshow looks good:
![screen shot 2015-09-24 at 2 44 51 pm](https://cloud.githubusercontent.com/assets/8808771/10083087/d5955b0c-62ca-11e5-8d36-3a347b2dc852.png)

**Comment by brandon-rhodes** [comment]
I have just checked off the second item here as done, because it looks like more work was done on the banner in 0eb41879b44 and because when testing the site under Firefox the banner now seems to shrink correctly and remain an appropriate width even as the window becomes very narrow. So this issue now looks to be complete!
